require 'nokogiri'

module Slaw
  module Render
    # Support for transforming XML AN documents into various forms,
    # currently focusing on HTML.
    class Transforms
      @@xslt = {
        :act => Nokogiri::XSLT(File.open(File.dirname(__FILE__) + '/xsl/act.xsl'))
      }

      def initialize
      end

      # Transform an XML document +doc+ (a Nokogiri::XML::Document object) into HTML.
      # Specify +base_url+ to manage the base for relative URLs generated by
      # the transform.
      def act_to_html(doc, base_url='')
        params = { 'base_url' => base_url }

        @@xslt[:act].transform(doc, Nokogiri::XSLT.quote_params(params)).to_s
      end
    end
  end
end
